/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

CREATE TABLE IF NOT EXISTS `caretaker` (
  `USERNAME` varchar(50) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `PASSWORD` varchar(50) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `NAME` varchar(10) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `COMPANY_NAME` char(70) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS `company` (
  `COMPANY_NAME` char(70) NOT NULL,
  `PROVINCE` char(50) DEFAULT NULL,
  `DISTRICT` char(50) DEFAULT NULL,
  `SUB_DISTRICT` char(50) DEFAULT NULL,
  `POSTAL_CODE` varchar(6) DEFAULT NULL,
  `TEL` varchar(10) DEFAULT NULL,
  `E-MAIl` varchar(70) DEFAULT NULL,
  PRIMARY KEY (`COMPANY_NAME`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;

CREATE TABLE IF NOT EXISTS `cooperative_education` (
  `USER_ID` varchar(13) NOT NULL,
  `PASSWORD` varchar(50) DEFAULT NULL,
  `USER_TYPE` char(50) DEFAULT NULL,
  PRIMARY KEY (`USER_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;

CREATE TABLE IF NOT EXISTS `department` (
  `Department_id` varchar(50) NOT NULL,
  `Department_name` char(70) DEFAULT NULL,
  PRIMARY KEY (`Department_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;

CREATE TABLE IF NOT EXISTS `education_background` (
  `USER_ID` varchar(13) NOT NULL,
  `EDUCATIONAL_RECORD` char(50) DEFAULT NULL,
  `EDUCATIONAL_NAME` char(50) DEFAULT NULL,
  `MAJOR` char(30) DEFAULT NULL,
  `GRADUATION_YEAR` char(10) DEFAULT NULL,
  PRIMARY KEY (`USER_ID`),
  CONSTRAINT `FK_education_background_personal_data` FOREIGN KEY (`USER_ID`) REFERENCES `personal_data` (`USER_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;

CREATE TABLE IF NOT EXISTS `family_information` (
  `USER_ID` varchar(13) NOT NULL,
  `NAME_SURNAME` char(50) DEFAULT NULL,
  `OCCUPATION` char(50) DEFAULT NULL,
  `AGE_FAM` char(10) DEFAULT NULL,
  `HAS_SIBLINGS` int DEFAULT NULL,
  `SEX` char(10) DEFAULT NULL,
  `IS_SON_OF` int DEFAULT NULL,
  PRIMARY KEY (`USER_ID`),
  CONSTRAINT `FK_family_information_personal_data` FOREIGN KEY (`USER_ID`) REFERENCES `personal_data` (`USER_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;

CREATE TABLE IF NOT EXISTS `personal_data` (
  `USER_ID` varchar(13) NOT NULL,
  `PREFIX_STUDENT` char(10) DEFAULT NULL,
  `NAME_SURNAME` char(60) DEFAULT NULL,
  `COURSE` char(50) DEFAULT NULL,
  `BRANCH` char(50) DEFAULT NULL,
  `GROUP` char(50) DEFAULT NULL,
  `YEAR` int DEFAULT NULL,
  `ADVISOR` char(50) DEFAULT NULL,
  `GPA_PREVIOUS` float DEFAULT NULL,
  `CUMULATIVE_GPA` float DEFAULT NULL,
  `Department_id` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`USER_ID`),
  KEY `FK_personal_data_department` (`Department_id`),
  CONSTRAINT `FK_personal_data_department` FOREIGN KEY (`Department_id`) REFERENCES `department` (`Department_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;

CREATE TABLE IF NOT EXISTS `personcon_address` (
  `ID_CARD` varchar(13) NOT NULL,
  `HOUSE_NO` varchar(10) DEFAULT NULL,
  `VILLAGE_NO` varchar(60) DEFAULT NULL,
  `ALLEY` char(50) DEFAULT NULL,
  `LANE` char(50) DEFAULT NULL,
  `ROAD` char(50) DEFAULT NULL,
  `SUB_DISTRICT` char(50) DEFAULT NULL,
  `SUB_AREA` char(50) DEFAULT NULL,
  `DISTRICT` char(50) DEFAULT NULL,
  `PROVINCE` char(50) DEFAULT NULL,
  `POSTAL_CODE` char(6) DEFAULT NULL,
  PRIMARY KEY (`ID_CARD`),
  CONSTRAINT `FK_personcon_address_person_contact` FOREIGN KEY (`ID_CARD`) REFERENCES `person_contact` (`ID_CARD`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;

CREATE TABLE IF NOT EXISTS `person_contact` (
  `ID_CARD` varchar(13) NOT NULL,
  `PERFIX_CON` char(30) DEFAULT NULL,
  `NAME_SURNAME` char(50) DEFAULT NULL,
  `RELATED` char(30) DEFAULT NULL,
  `TEL_CON` char(10) DEFAULT NULL,
  `USER_ID` varchar(13) DEFAULT NULL,
  PRIMARY KEY (`ID_CARD`),
  KEY `FK_person_contact_cooperative_education` (`USER_ID`),
  CONSTRAINT `FK_person_contact_cooperative_education` FOREIGN KEY (`USER_ID`) REFERENCES `cooperative_education` (`USER_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;

CREATE TABLE IF NOT EXISTS `position_duration` (
  `USER_ID` varchar(13) NOT NULL,
  `START_WORK` date DEFAULT NULL,
  `END_WORK` date DEFAULT NULL,
  `term` char(30) DEFAULT NULL,
  `COMPANY_NAME` char(70) DEFAULT NULL,
  PRIMARY KEY (`USER_ID`),
  KEY `FK_position_duration_company` (`COMPANY_NAME`),
  CONSTRAINT `FK_position_duration_company` FOREIGN KEY (`COMPANY_NAME`) REFERENCES `company` (`COMPANY_NAME`),
  CONSTRAINT `FK_position_duration_personal_data` FOREIGN KEY (`USER_ID`) REFERENCES `personal_data` (`USER_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;

CREATE TABLE IF NOT EXISTS `student_address` (
  `USER_ID` varchar(13) NOT NULL,
  `HOUSE_NO` varchar(50) DEFAULT NULL,
  `VILLAGE_NO` varchar(50) DEFAULT NULL,
  `ALLEY` char(50) DEFAULT NULL,
  `LANE` char(50) DEFAULT NULL,
  `ROAD` char(50) DEFAULT NULL,
  `SUB_DISTRICT` char(50) DEFAULT NULL,
  `SUB_AREA` char(50) DEFAULT NULL,
  `DISTRICT` char(50) DEFAULT NULL,
  `PROVINCE` char(50) DEFAULT NULL,
  `POSTAL CODE` varchar(6) DEFAULT NULL,
  `TEL.` varchar(10) DEFAULT NULL,
  `MOBILE PHONE` varchar(10) DEFAULT NULL,
  `E-MAIL` varchar(70) DEFAULT NULL,
  `STATUS_RESIDENCE` varchar(50) DEFAULT NULL,
  `HEIGHT` int DEFAULT NULL,
  `WEIGHT` int DEFAULT NULL,
  `CONGENITAL_DISEASE` char(100) DEFAULT NULL,
  PRIMARY KEY (`USER_ID`),
  CONSTRAINT `FK_student_address_personal_data` FOREIGN KEY (`USER_ID`) REFERENCES `personal_data` (`USER_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;

CREATE TABLE IF NOT EXISTS `talent` (
  `USER_ID` varchar(13) NOT NULL,
  `talent` char(100) DEFAULT NULL,
  PRIMARY KEY (`USER_ID`),
  CONSTRAINT `FK_talent_personal_data` FOREIGN KEY (`USER_ID`) REFERENCES `personal_data` (`USER_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;

/*!40103 SET TIME_ZONE=IFNULL(@OLD_TIME_ZONE, 'system') */;
/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IFNULL(@OLD_FOREIGN_KEY_CHECKS, 1) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40111 SET SQL_NOTES=IFNULL(@OLD_SQL_NOTES, 1) */;
